### ISSUE TITLE
有没有比较新的msi b360m mortar 9400 核心显卡 配置的oc的efi？

### ISSUE THREAD

**Issue by cmj799** [leehiuleong/MSI_B360M_Mortar-i5-9400_Hackintosh_EFI#1]
原配置已经不够用了，血书作者更新！！！！

**Comment by leehiuleong** [comment]
现在用的是GitHub上找的别人的oc EFI，release里有较多版本，下载only iGPU
https://github.com/SuperNG6/MSI-B360-Catalina-EFI/releases

**Comment by cmj799** [comment]
谢谢！！！！！
